import mongoose from 'mongoose';

export const getTaskSeeds = (userIds: mongoose.Types.ObjectId[]) => [
  {
    userId: userIds[0],
    title: 'Complete Project Proposal',
    description: 'Finish the draft for the new server project.',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000 * 2),
  },
  {
    userId: userIds[1],
    title: 'Buy Groceries',
    description: 'Milk, Eggs, Bread, and Fruits.',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000),
  },
  {
    userId: userIds[2],
    title: 'Fix Bug #123',
    description: 'Resolve the login issue on mobile devices.',
    priority: 'high',
    status: 'completed',
    completedDate: new Date(),
  },
  {
    userId: userIds[3],
    title: 'Design UI Mockups',
    description: 'Create Figma designs for the dashboard.',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000 * 5),
  },
  {
    userId: userIds[4],
    title: 'Research AWS Lambda',
    description: 'Look into serverless options for the API.',
    priority: 'low',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000 * 7),
  },
  {
    userId: userIds[5],
    title: 'Team Meeting',
    description: 'Weekly sync with the development team.',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000 * 1),
  },
  {
    userId: userIds[6],
    title: 'Update Documentation',
    description: 'Refactor the README file.',
    priority: 'low',
    status: 'completed',
    completedDate: new Date(Date.now() - 86400000),
  },
  {
    userId: userIds[7],
    title: 'Review Pull Request',
    description: 'Review the latest changes from the team.',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000 * 3),
  },
  {
    userId: userIds[8],
    title: 'Prepare Presentation',
    description: 'Slides for the monthly review.',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000 * 4),
  },
  {
    userId: userIds[9],
    title: 'Clean Up Workspace',
    description: 'Organize files and folders.',
    priority: 'low',
    status: 'pending',
    dueDate: new Date(Date.now() + 86400000 * 6),
  },
];
